-   id: velin
    name: Velin
    description: This hook attempt to reformat docstrings using numpydoc format.
    entry: velin
    language: python
    language_version: python3
    types: [text]
    types_or: [python]
    args: ["--write","--no-fixers"]
